# Generated by Django 4.2.5 on 2023-10-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_videochunk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='upload_data',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='video',
            name='Video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='videochunk',
            name='chunk_number',
            field=models.IntegerField(),
        ),
    ]
