# Generated by Django 4.2.5 on 2023-10-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_rename_upload_data_video_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(),
        ),
    ]
