# Generated by Django 4.2.5 on 2023-10-01 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0004_alter_video_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='completed',
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videochunk',
            name='chunk_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='videochunk',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link.video'),
        ),
    ]
