# Generated by Django 4.2.5 on 2023-10-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0005_remove_video_completed_video_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
        migrations.AddField(
            model_name='video',
            name='processing_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20),
        ),
    ]
