# Generated by Django 4.2.5 on 2023-10-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0006_remove_video_video_url_video_processing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='processing_status',
            field=models.CharField(choices=[('in_progress', 'Processing In Progress'), ('completed', 'Processing Completed'), ('failed', 'Processing Failed')], default='in_progress', max_length=20),
        ),
    ]
